#toml 格式的文件,建议字符串使用单引号,大小敏感
#

SubAddresses = '9.15.1.1:443,n-us1.libragen.cn:80'# 可以被广域网访问的域名端口,可以是域名也可以是ip,多个地址用逗号分隔
Port = '80' # 服务的端口,可以是80,443,在大陆其他的端口不能被访问
RegisterUrl = 'https://unchainadmin.pages.dev/api/nodes' #主控服务器地址,主要作用是控制用户授权和流量计费,可以为空则为个人模式
RegisterToken = 'unchain.people.from.censorship.and.surveillance'# 主控服务器的token
AllowUsers = '6fe57e3f-e618-4873-ba96-a76adec22ccd,6fe57e3f-e618-4873-ba96-a76adec22cce' # UUID 可以访问的用户UUID,多个则用逗号分隔.个人模式这里不能为空 在线UUID生成器 https://1024tools.com/uuid
LogFile = 'unchain.log' # 日志文件名,可以为空则不记录日志
DebugLevel = 'debug' # 日志基本debug, info, warn, error
IntervalSecond = '7200' #主控服务器推送流量数据的间隔,个人模式不关心



